# Generated by Django 5.0.6 on 2024-06-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='homebookingitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('heading', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('content1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='homecooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=100, null=True)),
                ('header', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('content1', models.TextField()),
                ('btn', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
