# Generated by Django 5.0.6 on 2024-06-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0002_homebookingitem_homecooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='homefeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
