# Generated by Django 5.0.6 on 2024-06-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0003_homefeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('btn', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
