# Generated by Django 5.0.6 on 2024-06-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0004_homeitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homeitems',
        ),
    ]
