# Generated by Django 5.0.6 on 2024-06-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0007_homefoodmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='homebookingtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobilenum', models.CharField(max_length=10)),
                ('datefield', models.DateField()),
                ('timefield', models.TimeField()),
                ('type', models.CharField(choices=[('guest1', 'guest1'), ('guest2', 'guest2'), ('guest3', 'guest3'), ('guest4', 'guest4'), ('guest5', 'guest5')], max_length=10, null=True)),
            ],
        ),
    ]
