# Generated by Django 5.0.6 on 2024-06-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0012_hometestimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='homefoodblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('btn', models.CharField(max_length=100)),
            ],
        ),
    ]
