# Generated by Django 5.0.6 on 2024-06-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0013_homefoodblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='commetus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
