# Generated by Django 5.0.6 on 2024-06-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0015_homefeaturemenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homefeaturemenu',
        ),
    ]
