# Generated by Django 5.0.6 on 2024-06-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0016_delete_homefeaturemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='homefeaturemenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
