# Generated by Django 5.0.6 on 2024-06-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0020_remove_commetus_website_commetus_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='commetus',
        ),
    ]
