# Generated by Django 5.0.6 on 2024-06-24 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0022_commetus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commetus',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
