# Generated by Django 5.0.6 on 2024-06-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0028_foodsnackitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='foodburgeritems',
        ),
    ]
