# Generated by Django 5.0.6 on 2024-06-27 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0029_delete_foodburgeritems'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('fats', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitamins', models.TextField()),
                ('minerals', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SnackIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='snack_images/')),
                ('availability', models.CharField(max_length=255)),
                ('nutrition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='three_app.nutrition')),
                ('snackingredients', models.ManyToManyField(to='three_app.snackingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='three_app.snack')),
            ],
        ),
    ]
