# Generated by Django 5.0.6 on 2024-06-27 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0030_nutrition_snackingredient_snack_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='snackingredients',
        ),
    ]
