# Generated by Django 5.0.6 on 2024-06-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0031_remove_snack_snackingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
