# Generated by Django 5.0.6 on 2024-06-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0032_delete_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='foodsnackitems',
        ),
    ]
