# Generated by Django 5.0.6 on 2024-06-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0034_rename_title_snack_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='category',
            field=models.CharField(default='burger', max_length=50),
        ),
        migrations.AddField(
            model_name='snack',
            name='category',
            field=models.CharField(default='snack', max_length=50),
        ),
    ]
