# Generated by Django 5.0.6 on 2024-07-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0039_rename_header_foodpizza_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('fat', models.CharField(max_length=20)),
                ('carbohydrates', models.CharField(max_length=20)),
                ('protein', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('size_options', models.JSONField()),
                ('customization_options', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='pizza_images/')),
                ('availability', models.CharField(max_length=100)),
                ('nutrition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='three_app.pizzanutrition')),
            ],
        ),
    ]
