# Generated by Django 5.0.6 on 2024-07-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0041_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
