# Generated by Django 5.0.6 on 2024-07-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_app', '0044_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
